service: apirest-mercadolibre-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(./serverless_ssm.yml)}

plugins:
  - serverless-offline-ssm
  - serverless-offline

functions:
  hello:
    handler: src/lambdas/test/hello.handler
    events:
      - http:
          path: /test
          method: get
          private: true
  database:
    handler: src/lambdas/db/connection.handler
    events:
      - http:
          path: /db-connection
          method: get
          private: true
  getAllUsers:
    handler: src/lambdas/users/getAll.handler
    events:
      - http:
          path: /users/list
          method: get
          private: true
  getByIdUsers:
    handler: src/lambdas/users/getById.handler
    events:
      - http:
          path: /users/id/{id}
          method: get
          private: true

resources:
  - ${file(src/resources/api-gateway.yml)}

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
  serverless-offline-ssm:
    stages:
      - dev
    ssm: ${file(./serverless_ssm.yml)}
