service: apirest-mercadolibre-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(./serverless_ssm.yml)}

plugins:
  - serverless-offline-ssm
  - serverless-offline

functions:
  helloTest:
    handler: src/controllers/test/hello.handler
    events:
      - http:
          path: /test
          method: get
          private: true
  databaseTest:
    handler: src/controllers/db/connection.handler
    events:
      - http:
          path: /db-connection
          method: get
          private: true
  getAllUsers:
    handler: src/controllers/users/getAll.handler
    events:
      - http:
          path: /users/list
          method: get
          private: true
  getByIdUsers:
    handler: src/controllers/users/getById.handler
    events:
      - http:
          path: /users/id/{id}
          method: get
          private: true
  getLikeNicknameUsers:
    handler: src/controllers/users/getLikeNickname.handler
    events:
      - http:
          path: /users/nickname/{nickname}
          method: get
          private: true            
  getLikeFirstNameUsers:
    handler: src/controllers/users/getLikeFirstName.handler
    events:
      - http:
          path: /users/first-name/{firstName}
          method: get
          private: true          
  getLikeLastNameUsers:
    handler: src/controllers/users/getLikeLastName.handler
    events:
      - http:
          path: /users/last-name/{lastName}
          method: get
          private: true  
  getLikeIdentificationTypeUsers:
    handler: src/controllers/users/getLikeIdentificationType.handler
    events:
      - http:
          path: /users/identification-type/{identificationType}
          method: get
          private: true  

resources:
  - ${file(src/resources/api-gateway.yml)}

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
  serverless-offline-ssm:
    stages:
      - dev
    ssm: ${file(./serverless_ssm.yml)}
