
service: apirest-mercadolibre-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout : 10
  environment: 
    ${file(serverless_ssm.yml)}

plugins:
  - serverless-offline-ssm
  - serverless-offline

custom:
  serverless-offline-ssm:
    stages:
      - dev
    ssm:
      '/hello_test': 'HELLO SSM'
  serverless-offline:
    httpPort: 4000

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /users/create
          method: get

resources:
